/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sistemaPraia.telas;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.awt.image.DataBufferByte;
import org.opencv.core.Core;
import org.opencv.core.Mat;
import org.opencv.videoio.VideoCapture;

/**
 *
 * @author PC
 */
public class Painel extends javax.swing.JPanel implements Runnable{
private VideoCapture video;
private Mat frame;
private BufferedImage buffer;
   

    public Painel() {
        initComponents();
         System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        new Thread(this).start();
    }  
       
       
     @Override    
    public void run() {
      this.video = new VideoCapture();
        this.frame = new Mat();
        if(video.isOpened())
            while (true) {
                video.read(frame);
                if(!frame.empty()){
                    MatToBufferImage(frame);
                    this.repaint();
                }
            }
        
        
    }
    
    
    public void paintCamponente(Graphics g){
        super.paintComponent(g);
    if(buffer== null){
    return;
    
    }
    g.drawImage(buffer, 10,10,buffer.getHeight(), buffer.getHeight(), this);
    }
    
    private void MatToBufferImage(Mat mat) {
        
        
        int altura = mat.width();
        int largura = mat.height();
        int canais = mat.channels();
        byte [] source = new byte[altura* largura *canais];
        mat.get(0,0, source);
        buffer = new BufferedImage(altura, largura, BufferedImage.TYPE_3BYTE_BGR);
        final byte[] saida =((DataBufferByte) buffer.getRaster().getDataBuffer()).getData();
        
        System.arraycopy(source, 0, saida, 0, source.length);
        
      
    }

    /**
     * Creates new form Painel
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
